[tool.ruff]
include = [
    "tests/**/*.py",
    "sphinxcontrib/**/*.py",
    "doc/**/*.py"
]
indent-width = 4
line-length = 88

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
fixable = ["ALL"]
ignore = [
"D203",
"E203",
"PERF203",
"PERF401",
"PERF403",
"RUF001",
"RUF012",
"SIM102",
]
# List of all the ruff rules (includes why the rule matters)
# https://docs.astral.sh/ruff/rules/
select = [
    "C",
    "C4",
    "E9",
    "F63",
    "F7",
    "F82",
    "FLY",
    "I",
    "PERF",
    "RUF",
    "SIM",
    "W"
]
unfixable = []

[tool.ruff.lint.mccabe]
max-complexity = 51

[tool.codespell]
builtin = "clear,rare"
ignore-words = ".github/codespell_ignore_words.txt"
skip = "./.git"


[tool.pytest.ini_options]
addopts = "-ra --strict-config --strict-markers --show-capture=all --showlocals -s -vv --cov=sphinxcontrib --cov=tests --cov-report=term"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS"
junit_family = "xunit2"
log_cli_level = "INFO"
xfail_strict = true

[tool.coverage.run]
branch = true
omit = [
    '*/_build/*',
    'sphinxcontrib/__init__.py',
]


# Please update the GitHub Actions workflow if you change the envlist here
[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{310,311,312,313,314}-sphinx{70,latest}

[testenv]
passenv =
    USERNAME
    PY_COLORS
    FORCE_COLOR
    NO_COLOR
    CLICOLOR
    CLICOLOR_FORCE
deps =
    pytest
    pytest-cov
    defusedxml
    sphinx70: Sphinx>=7.0,<8.0
    sphinxlatest: Sphinx
    sphinxdev: https://github.com/sphinx-doc/sphinx/archive/refs/heads/master.zip
commands =
    pytest {posargs}
    sphinx-build -b html -d {envtmpdir}/doctrees tests/test_docs {envtmpdir}/html
"""

